# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a14e8c5875cb4ee81c8857a78ebd386de4881960f49cd9065b7622a16bfb4cf8c3eb5577701484a0bb44359a4e34284e147cc8e1d90d62cc4969464c7512fae

test:
  secret_key_base: 7cbbeba416234bec473c1323772c80830a238eefa65815e71fa6bc599e65f8f0a8c8da628c09816e76c8a277f9ed528ef70d9394de64582bf65ba6067c02a882

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
